// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Estadísticas de transmisión de un frame de video analítica
 */
export type CvaFrameStats = { bytes_sent: number, latency_ms: number, total_frames: number, fps_real: number, };
