// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuración de gestos y muestreo para CVA
 */
export type CvaGestureConfig = { enabled: boolean, min_confidence: number, mapping: Record<string, string>, };
