// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Información de la sesión activa de control por gestos
 */
export type CvaGestureSession = { session_id: string, module_id: string, bridge_port: number, active: boolean, };
