// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requisitos de ejecución **declarativos**: describen qué tipo de entorno
 * necesita la práctica (para poder buscar un `LabConnectionProfile` local
 * compatible), nunca un destino de red concreto.
 */
export type ExecutionRequirements = { connection_type: string, capabilities: Array<string>, };
