// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionRequirements } from "./ExecutionRequirements";
import type { PracticeAuthor } from "./PracticeAuthor";
import type { PracticeMaterial } from "./PracticeMaterial";
import type { PracticeSource } from "./PracticeSource";
import type { ProcedureStep } from "./ProcedureStep";

/**
 * Práctica tal como la publica la API externa de autoría. Ver el módulo
 * para la nota de modelo de confianza — este tipo nunca debe ganar un
 * campo de conexión real.
 */
export type ExternalLabPractice = { id: string, version: number, title: string, description: string, area: string, level: string, objectives: Array<string>, materials: Array<PracticeMaterial>, procedure: Array<ProcedureStep>, safety_measures: Array<string>, estimated_duration_minutes: number, status: string, execution_requirements: ExecutionRequirements, author: PracticeAuthor, source: PracticeSource, updated_at: string, };
