// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cámara del NVR, ya lista para consumir desde el frontend.
 * `stream_url` es la URL HLS completa contra el broker (nunca contra
 * Shinobi directo, nunca con la API key real embebida) — el frontend la
 * pasa directo a `HlsPlayer`, igual que antes con `CameraInfo`.
 */
export type NvrCamera = { id: string, name: string, status: string, stream_url: string, };
