// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cámara del NVR, ya lista para consumir desde el frontend.
 * `stream_url` es la URL HLS completa contra el broker (nunca contra
 * Shinobi directo, nunca con la API key real embebida) — el frontend la
 * pasa directo a `HlsPlayer`, igual que antes con `CameraInfo`.
 */
export type NvrCamera = { id: string, name: string, status: string, stream_url: string, 
/**
 * No todas las cámaras del NVR son PTZ — el broker lo indica por cámara
 * (`PTZ_CAMERAS_JSON` en la Pi) según qué modelos exponen la API HTTP
 * de Reolink en la red. El frontend solo muestra el control si es true.
 */
ptz: boolean, };
