// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cámara del NVR, ya lista para consumir desde el frontend.
 * `stream_url` es la URL HLS completa (api key incluida por Shinobi) —
 * el frontend la pasa directo a `HlsPlayer`, igual que antes con `CameraInfo`.
 */
export type NvrCamera = { id: string, name: string, status: string, stream_url: string, };
