// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resultado de un comando PTZ — solo confirma que el broker lo aceptó y lo
 * reenvió a la cámara; el movimiento en sí no tiene feedback síncrono.
 */
export type PtzCommandResult = { ok: boolean, };
