// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SesionPractica } from "./SesionPractica";

export type ResumenSesiones = { generado: string, dias: number, 
/**
 * Más recientes primero.
 */
sesiones: Array<SesionPractica>, };
