// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Una sesión de práctica tal como la guarda el broker.
 */
export type SesionPractica = { id: string, sesion_id: string, usuario: string, nombre: string | null, correo: string | null, practica_id: string | null, practica_nombre: string | null, 
/**
 * ISO 8601 (UTC)
 */
inicio: string, ultimo_latido: string, 
/**
 * `None` mientras la sesión sigue activa.
 */
fin: string | null, 
/**
 * "cliente" (se cerró la práctica) | "sin_latido" (app cerrada o sin red)
 */
cierre: string | null, ip: string | null, 
/**
 * Barrio y/o ciudad: por IP (aprox.) o del dispositivo vía Nominatim.
 */
ciudad: string | null, region: string | null, pais: string | null, lat: number | null, lon: number | null, 
/**
 * "ip" (aprox. nivel ciudad) | "dispositivo" (servicio de ubicación del equipo)
 */
fuente_ubicacion: string | null, 
/**
 * Precisión reportada por el equipo, en metros (solo fuente "dispositivo").
 */
precision_m: number | null, };
