// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocalEntry = { name: string, path: string, kind: string, size?: bigint, mtime?: bigint, };
