@startuml TopologiaFisicaClienteSSHUnipiloto
title Arquitectura Conección Remota Unipiloto

skinparam backgroundColor #f8f9fa
skinparam defaultTextColor #212529
skinparam componentStyle rectangle
skinparam shadowing false

rectangle "Puesto del usuario\n(Estudiante / Profesor)" as UserPC {
  rectangle "Cliente desktop\nTauri + Rust + React" as DesktopApp
  rectangle "Disco local\n(SavedHosts/)" as LocalFS
  rectangle "OS keyring\n(master key)" as Keyring
}

rectangle "Internet" as Internet

package "Campus universidad" as Campus {
  rectangle "Servidor Moodle LMS\n(API REST)" as Moodle
  rectangle "BD Moodle\n(Reportes, logs, progresos)" as MoodleDB
  rectangle "Servidor LDAP\n(Directorio activo)" as LDAP

  package "Red laboratorio fisico" as LabNet {
    rectangle "Servidores Linux\nlaboratorio" as LabLinux
  }
}

package "Servicios cloud" as Cloud {
  rectangle "db\n(storage, logs, reportes)" as Supabase
  rectangle "APIs IA\n(API propia, Claude, OpenAI)" as AI
  rectangle "GitHub + GIT" as GH
}

UserPC -down- Internet
DesktopApp -right- LocalFS : Lectura/Escritura\nSistema de archivos
DesktopApp -down- Keyring
Internet -down- LabNet : SSH / SFTP
Internet -right- Moodle : HTTPS REST
Moodle -down- MoodleDB 
Internet -right- LDAP
Internet -up- Supabase
Internet -up- AI : HTTPS/ TOML
Internet -up- GH

@enduml

